---
sudo: false

env:
  global:
    - ROUNDCUBE_VERSION="$(<version)"

services:
  - docker

before_script:
  - npm install -g snyk
  - snyk auth "${SNYK_API_TOKEN}"

script:
  - docker build --build-arg "ROUNDCUBE_VERSION=${ROUNDCUBE_VERSION}" -t roundcube .
  - snyk test --docker roundcube

before_deploy:
  - if test -n "${TRAVIS_TAG}"; then
      docker tag roundcube "ushi/roundcube:${TRAVIS_TAG}" &&
        snyk monitor --docker "ushi/roundcube:${TRAVIS_TAG}";
    else
      docker tag roundcube "ushi/roundcube:latest";
    fi
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

deploy:
  - provider: script
    skip_cleanup: true
    script: docker push "ushi/roundcube:${TRAVIS_TAG}"
    on:
      tags: true

  - provider: script
    skip_cleanup: true
    script: docker push "ushi/roundcube:latest"
    on:
      branch: master
