---
name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: build
        run: docker build --build-arg "ROUNDCUBE_VERSION=$(<version)" -t roundcube .
      - name: push
        env:
          GITHUB_REGISTRY_TOKEN: ${{ secrets.GITHUB_REGISTRY_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u ushis -p "${GITHUB_REGISTRY_TOKEN}"
          docker tag roundcube "docker.pkg.github.com/ushis/roundcube-docker/roundcube:${GITHUB_SHA:0:7}"
          docker push "docker.pkg.github.com/ushis/roundcube-docker/roundcube:${GITHUB_SHA:0:7}"
